Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 30
  Enabled: true
  Severity: Convention
Lint/NotNil:
  Enabled: false
Style/VerboseBlock:
  Enabled: false